### ISSUE TITLE
Resolve carriage stop after "J" in gcode

### ISSUE THREAD

**Issue by nwrancher** [MaslowCNC/GroundControl#130]
Current configuration of Ground Control will pause after J commands in the g code.  I was able to replicate the behavior using both the Dragon.nc and BiggerMotorMount25in.nc files found in the "gcodefortesting" folder in GroundControl-Master.

**Comment by johnbenweber** [comment]
Can you describe the behavior? I'm just trying to get an idea of whether the issue is being caused by GroundControl or the Firmware. When you say pause do you mean that the machine briefly stops between commands but resumes on its own or does the execution of the gcode file pause requiring you to press the "run" button or something else?

**Comment by nwrancher** [comment]
The execution of the file pauses and requires pause/run to continue.  If 
time has passed it continues with loss of position.

**Comment by BarbourSmith** [comment]
Is this issue still open? I haven't heard about it in a little while, but it's a top priority bug if it's still active and I don't want to neglect it.

**Comment by nwrancher** [comment]
Resolved with changing to GRBL gcode output.
