### ISSUE TITLE
Define Origin changes mm to inches

### ISSUE THREAD

**Issue by GeroBH** [MaslowCNC/GroundControl#166]
On
Ubuntu 14.04.5 LTS trusty
Python 2.7.6
Dragon.nc loaded
not connected

Clicking "Define Origin" changes mm to inches.

**Comment by BarbourSmith** [comment]
Good catch!

This one is a little tricky. What's happening is that "define origin" is reloading the gcode file and setting the units to the units of the file. If the file is saved in mm that's mm, if it's in inches its inches.

I think that the real issue is maybe that you can switch units with a file open? Like if I open a file in inches, switch to mm what does that really mean? As soon as I click "run" the machine will switch back to inches mode (otherwise the part would be huge), but the units will display incorrectly (I believe).

So the real question is what is the right behavior for the situation where you open a file with units of inches, switch the machine to mm, then press "Run"?

**Comment by GeroBH** [comment]
It is not an issue then, it's correct behaviour and can be closed. I think we can fairly assume that a user who prefers metric, will have his CAD/CAM setup in mm. Most sharing of designs will be on CAD level. If a user wants to use a .nc file shared with him, he should accept any unit it is created with. -> Joke: Unless you want to program a real-time unit conversion into GrondContol :-)
