### ISSUE TITLE
Triangular calibration uses default value instead of previous value

### ISSUE THREAD

**Issue by blurfl** [MaslowCNC/GroundControl#482]
Trying to do the calibration step with a top-pantograph linkage (129mm rotationradius), I find that choosing the Triangular calibration writes 260 to rotationradius in groundcontrol.ini overwriting the previous value. That should not happen. Version 0.99 as of this morning.

 Further, couldn't we check and use the previous value if it is present? That, and allow the user to input an approximate value when choosing Triangular similar to the step in Quad. that makes an estimate based on chain links.

**Comment by BarbourSmith** [comment]
Yes! This is something I've been thinking about. I think I'm going to remove the step where you count the links and put a new step after choosing the kinematics type which asks for a guess at the radius or distance between attachment points.

The work around is that as is the calibration process just takes more tries to converge because the initial guess isn't right, but it will get there

**Comment by blurfl** [comment]
I've got a PR ready that looks for an existing value and uses that... I see that if groundcontrol.ini doesn'ty have a value for rotationRadius it puts 100 there.

**Comment by BarbourSmith** [comment]
Love it. That's already a huge step forwards, let's do it!

**Comment by blurfl** [comment]
Darn , I really didn't mean to open this branch on the upstream master 😧! What best to do?

**Comment by blurfl** [comment]
Fixed PR#484
