### ISSUE TITLE
gcodeCanvas.py reloadGcode() converts parameters to e-notation, causes incorrect operation

### ISSUE THREAD

**Issue by blurfl** [MaslowCNC/GroundControl#676]
The function reloadGcode() reads in lines from the disk file into a list 'filtersparsed' and formats them for GC. When that formatting is finished, the parameters in the list still have their full values.
 Lines 141 and 142  assign the contents of 'filtersparsed' to a global 'self.data.gcode'. After that assignment, parameters have been changed to e-notation in both 'filtersparsed' and 'self.data.gcode'.
 Presently, gcodeCanvas interprets parameters as values and ignores the exponent. Which approach would be a better fix?
 - prevent e-natation in creating self.data.gcode
 - re-write all function that use parameters to evaluate e-notation.

**Comment by BarbourSmith** [comment]
> prevent e-natation in creating self.data.gcode

Gets my vote. It seems like the values we are working are rarely so large that e-notation is necessary.  

Are we sure that the e-notation is actually a property of how the numbers are stored and not how they are printed? A print command on a floating point number might show an exponent notation while printing a number as a string won't, but really the number is the same in either case.

**Comment by BarbourSmith** [comment]
I think the issue is the str() function used when moving the gcode to a new location around line 417. 

We are taking the line of gcode, converting it into numbers, then converting it back to gcode at the new location, and to do that we need to convert a number into a string using the str() function. Unfortunately if the number has more than 15 digits to the left of the . or more than 4 digits to the right of the . it gets converted to scientific notation.

Here's a question on the topic:

https://stackoverflow.com/questions/38847690/convert-float-to-string-without-scientific-notation-and-false-precision

**Comment by blurfl** [comment]
The e-notation was introduced in version v0.66; prior to that, e-notation did not occur and rendering was correct. That was last April 12, almost a year!

**Comment by davidelang** [comment]
in the format string for the output, there's a format that says decimal only, 
and does not allow scientific notation.

**Comment by blurfl** [comment]
You put your finger right on it - thanks for the coaching! PR#675 now renders correctly with an arbitrary number of digits beyond the decimal point, and displays the parameters in decimal notation. 
Note that the PR in its present form truncates the display of the parameters at six digits past the decimal point. That can be addressed in the format statement introduced in the PR.

**Comment by davidelang** [comment]
On Fri, 30 Mar 2018, Scott Smith wrote:

> Note that the PR in its present form truncates the display of the parameters 
> at six digits past the decimal point. That can be addressed in the format 
> statement introduced in the PR.

since an arc with the same start and end point becomes a circle, we need to have 
a test to see if the start and end are the same after the truncation, and only 
allow it if they are also the same before the truncation.

otherwise CAM programs that output stupidly small arcs end up cutting lots of 
full circles instead.

David Lang

**Comment by blurfl** [comment]
I think PR #677 addressed this. Close it?
