### ISSUE TITLE
Preset offset for Z 0 (enhancement, help needed)

### ISSUE THREAD

**Issue by GeroBH** [MaslowCNC/GroundControl#756]
Can we have an editable offset value for Z 0?
It would open for 'out of the box' ideas to set zero Z.

**Comment by GeroBH** [comment]
Closing this until I have a working proof. What I need to experiment is already available in the Z menu.

**Comment by blurfl** [comment]
The G10 gcode lets one set the value for an axis. 

 In it's present form, the firmware that handles the G38.2 gcode sets the Z value to 0 without the G10 gcode instead of simply stopping the Z axis travel and requiring the user to send G10 Z0 to zero the Z at the touch-point. 
 For your testing, in your macro after the G38.2, you could put a G10 Znnn gcode with the nnn value of your sled and sensor thickness if the touchpoint is above the sole of the sled.
 When you're ready for an enhancement request, it would probably belong in the Firmware repository, the change needs to happen in cnc_ctrl_v1/GCode.cpp around lines 856, 857 or so.
